version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:
  autoserver:
    image: 19mikel95/pymodmikel:autoserversynchub
    container_name: autoserver
    command: sh -c "
      sed -i 's|localhost|0.0.0.0|g' sincserver.py;
      python3 sincserver.py daemon off"
    ports:
      - "5020:5020"
    restart: unless-stopped
    networks:
      - monitor-net

  clientperf:
    image: 19mikel95/pymodmikel:reloadcomp
    container_name: clientperf
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver