version: '2.1'
networks:
  monitor-net:
    driver: bridge

services:
  autoserver:
    image: 19mikel95/pymodmikel:autoserversynchub
    container_name: autoserver
    command: sh -c "
      sed -i 's|localhost|0.0.0.0|g' sincserver.py;
      python3 sincserver.py daemon off"
    ports:
      - "5020:5020"
    restart: unless-stopped
    networks:
      - monitor-net
    mem_limit: 256m

  clientperf1:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf1
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf2:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf2
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf3:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf3
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf4:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf4
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf5:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf5
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf6:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf6
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf7:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf7
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver

  clientperf8:
    image: 19mikel95/pymodmikel:autoclientimprove
    container_name: clientperf8
    restart: unless-stopped
    networks:
      - monitor-net
    depends_on:
      - autoserver
    environment:
      - AUTO_SERVER_HOST=autoserver
